### ISSUE TITLE
安装依赖失败

### ISSUE THREAD

**Issue by yao378186268** [jetlinks/jetlinks-ui-components#229]
<img width="1024" alt="image" src="https://github.com/jetlinks/jetlinks-ui-vue/assets/84838562/c0427f36-1d05-4dfe-b70b-fa32fa1b43b8">
刚拉的代码，node版本 v21.4.0，npm i 显示https://registry.jetlinks.cn/colorful/-/colorful-2.1.0.tgz 证书过期

**Comment by XieYongHong** [comment]
切换至dev分支
